import type { Metadata } from "next";
import "./global.css";
import Providers from "./providers";
import React from "react";
import LayoutWrapper from "@/components/layoutWrapper";

export const metadata: Metadata = {
  title: "Novel App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className="flex flex-col min-h-screen">
        <Providers>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </Providers>
      </body>
    </html>
  );
}